# Numpy

### 1. ndarray (Numpy Dimensional Array)

In [6]:
import numpy as np
a= np.array([1,4,5,8], float)
print(a)

[1. 4. 5. 8.]


In [7]:
a[3], a.dtype, a.shape

(8.0, dtype('float64'), (4,))

### 2. Array shape

In [ ]:
#1차원 - vector
a= np.array([1,4,5,8], float)

In [9]:
# 2차원 - matrix
m = [[1,4],[5,8]]
b = np.array(m, float)
print(b)

[[1. 4.]
 [5. 8.]]


In [11]:
# 3차원 - tensor
t = [[1,4],[5,8]],[[11,14],[15,18]]
c = np.array(t, float)
c

array([[[ 1.,  4.],
        [ 5.,  8.]],

       [[11., 14.],
        [15., 18.]]])

In [12]:
a.shape, b.shape, c.shape

((4,), (2, 2), (2, 2, 2))

In [13]:
# ndim
a.ndim, b.ndim, c.ndim

(1, 2, 3)

In [14]:
# size - element 개수
a.size, b.size, c.size

(4, 4, 8)

- reshape: size는 동일

In [15]:
c.reshape(2,4).shape

(2, 4)

In [17]:
c.reshape(2,4)

array([[ 1.,  4.,  5.,  8.],
       [11., 14., 15., 18.]])

In [19]:
# -1은 한번만 사용가능
c.reshape(-1,4)

array([[ 1.,  4.,  5.,  8.],
       [11., 14., 15., 18.]])

In [22]:
# flatten - 1차원으로 변경
c.flatten()

array([ 1.,  4.,  5.,  8., 11., 14., 15., 18.])

In [25]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [28]:
a = np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [30]:
a[0][1], a[0,1]

(1, 1)

In [33]:
#numpy에선 행과 열에대한 슬래싱을 할 수 있음
a[:,:2]

array([[0, 1],
       [3, 4]])

In [35]:
# 5, 6, 9, 10 으로 실습해보기
b = np.arange(16).reshape(-1,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [37]:
b[1:3, 1:3]

array([[ 5,  6],
       [ 9, 10]])

In [36]:
# 0, 1, 4, 5, 8, 9
b[:3, :2]

array([[0, 1],
       [4, 5],
       [8, 9]])

In [41]:
# 세번째 열까지는 X, 마지막 열은 Y
X, Y = b[:,:-1], b[:,:-1]
X.shape, Y.shape

((4, 3), (4, 3))

### 4. Creation

In [42]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
# 실수는 우리가 원하는 값을 정확하게 표현하지 못함
np.arange(0,1.1,0.1).tolist()[3] == 0.3

False

In [47]:
# 두 실수의 비교는 차이가 아주 작냐를 물어보는 것이 올바른 방법임
np.abs(np.arange(0,1.1,0.1).tolist()[3] - 0.3) < 1e-8

True

In [49]:
# ones, zeros, empty
a = np.zeros((5,), dtype=np.int8)
a

array([0, 0, 0, 0, 0], dtype=int8)

In [51]:
b = np.ones((2,4), dtype=np.int8)
b

array([[1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int8)

In [52]:
# 값을 모르니 일단 공간을 비워두는 것. zeros는 할당하기까지 한 것이나 empty는 빈칸만 생성 값을 모르니 일단 공간을 비워두는 것. zeros는 할당하기까지 한 것이나 empty는 빈칸만 생성
np.empty((2,5))
np.empty((2,5))

array([[0.1, 0.2, 0.3, 0.4, 0.5],
       [0.6, 0.7, 0.8, 0.9, 1. ]])

In [53]:
a = np.arange(24).reshape(4,-1)
np.ones_like(a)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [54]:
np.zeros_like(a)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [55]:
# 단위행렬: identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [56]:
# eye - 대각선이 1인 행렬
np.eye(3,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [57]:
np.eye(3,5,-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.]])

- Random sampling

In [58]:
np.random.seed(2021)
#균등분포
np.random.uniform(0,1,10).reshape(2,5)

array([[0.60597828, 0.73336936, 0.13894716, 0.31267308, 0.99724328],
       [0.12816238, 0.17899311, 0.75292543, 0.66216051, 0.78431013]])

In [59]:
#정규분포
np.random.normal(0,1,10).reshape(2,5)

array([[ 0.10641374,  0.42215483,  0.12420684, -0.83795346,  0.4090157 ],
       [ 0.10275122, -1.90772239,  1.1002243 , -1.40232506, -0.22508127]])

In [60]:
# 이항분포, 포아송분포, t분포, F분포
np.random.binomial(100,0.5,10)

array([46, 53, 57, 48, 57, 44, 40, 57, 54, 49])