### 0531 과제

In [2]:
import numpy as np

- 1. 넘파이를 사용하여 다음과 같은 행렬을 만든다.

In [3]:
a = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])
a

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

- 2. 다음 행렬과 같은 행렬이 있다

In [5]:
m = np.array([[0, 1, 2, 3, 4],
                [5, 6, 7, 8, 9],
                [10, 11, 12, 13,14]])

- 1) 이 행렬에서 값 7 을 인덱싱한다.

In [10]:
m[1,2]

7

- 2) 이 행렬에서 값 14 을 인덱싱한다.

In [11]:
m[-1,4]

14

- 3) 이 행렬에서 배열 [6,7] 을 슬라이싱한다.

In [18]:
m[1,1:3]

array([6, 7])

- 4) 이 행렬에서 배열 [7, 12] 을 슬라이싱한다.

In [13]:
m[1:,2]

array([ 7, 12])

- 5) 이 행렬에서 배열 [[3, 4], [8, 9]] 을 슬라이싱한다.

In [29]:
m[0:2, 3:]

array([[3, 4],
       [8, 9]])

- 3. 2번의 행렬 m을 1차원 벡터 f로 변환한 후 다음의 문제로 푸시오.

In [30]:
f = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])

- 1) 이 배열에서 3의 배수를 찾아라.

In [31]:
f[f%3==0]

array([ 0,  3,  6,  9, 12])

- 2) 이 배열에서 4로 나누면 1이 남는 수를 찾아라.

In [34]:
f[f%4==1]

array([ 1,  5,  9, 13])

- 3) 이 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라.

In [38]:
f[(f%3==0) & (f%4==1)]

array([9])

- 4. 값을 직접 입력하지 말고 우측의 행렬을 만드시오

In [55]:
b1 = np.eye(5,5,1)
b2 = np.eye(5,5) * 2
b3 = np.eye(5,5,-1) * 3
b = b1 + b2 + b3
b

array([[2., 1., 0., 0., 0.],
       [3., 2., 1., 0., 0.],
       [0., 3., 2., 1., 0.],
       [0., 0., 3., 2., 1.],
       [0., 0., 0., 3., 2.]])

- 5. 0에서 10까지 랜덤 실수값으로 이루어진 5 x 6 형태의 데이터 행렬을 만들고 이 데이터에
대해 다음과 같은 값을 구하시오.

In [7]:
c = np.random.uniform(0,10,30).reshape(5,6)
c

array([[3.71466189, 2.44679362, 9.62752867, 8.06005753, 6.3070975 ,
        5.63473335],
       [7.58999262, 3.34447522, 8.48603516, 3.4869251 , 1.98590888,
        7.65942952],
       [6.41144743, 7.63141921, 3.81268644, 2.96196358, 9.79183087,
        0.48984157],
       [4.66118827, 9.68035394, 1.30563753, 0.27037219, 7.0700185 ,
        5.41649786],
       [2.90871049, 6.83243208, 6.19302851, 8.79189267, 6.17831873,
        4.62278249]])

- 1) 전체의 최댓값

In [8]:
np.max(c)

9.791830867043133

- 2) 각 행의 합

In [12]:
np.sum(c, axis=1)

array([35.79087255, 32.5527665 , 31.09918909, 28.4040683 , 35.52716498])

- 3) 각 행의 최댓값

In [9]:
np.max(c, axis=1)

array([9.62752867, 8.48603516, 9.79183087, 9.68035394, 8.79189267])

- 4) 각 열의 평균

In [11]:
np.apply_along_axis(lambda a: np.average(a), 0, c) 

array([5.05720014, 5.98709481, 5.88498326, 4.71424222, 6.26663489,
       4.76465696])

- 5) 각 열의 최솟값

In [10]:
np.apply_along_axis(lambda a: np.min(a), 0, c) 

array([2.90871049, 2.44679362, 1.30563753, 0.27037219, 1.98590888,
       0.48984157])

- 6. 다음 배열은 첫번째 행(row)에 학번, 두번째 행에 영어 성적, 세번째 행에 수학 성적을 적은
배열이다. 영어 성적을 기준으로 각 열(column)을 재정렬하시오.

In [6]:
score=np.array([[  1,    2,    3,    4],
                [ 46,   99,  100,   71],
                [ 81,   59,   90,  100]])

score_rank=score[2].argsort()
scoreE=score.take(score_rank, axis=1)
print("ANSWER 1")
print(scoreE)

ANSWER 1
[[  2   1   3   4]
 [ 99  46 100  71]
 [ 59  81  90 100]]


- 7. 주사위를 100번 던지는 가상 실험을 파이썬으로 작성하고,
던져서 나오는 숫자의 평균을 구하시오.

In [3]:
d = np.random.randint(1, 7, size=100)
np.average(d)

3.24

- 8. 가격이 10,000원인 주식이 있다. 이 주식의 일간 수익률(%)은 기댓값이 0%이고 표준편차가 1%
인 표준 정규 분포를 따른다고 하자. 250일 동안의 주가를 무작위로 생성하시오.

In [3]:
np.random.randn(250)

array([ 1.52377941, -0.36653512, -1.2786485 ,  0.89007287, -1.36990799,
       -1.46307145,  1.65338716, -0.62340607,  0.03281971,  0.75729913,
        0.04498666,  0.81680969,  0.01964877,  0.33352446,  0.47686793,
       -0.6941358 ,  2.29513727,  0.33023981, -0.41245979, -0.87717456,
        0.73981295, -0.52457551,  0.62507972,  1.79854045,  1.96444654,
       -1.24220602, -1.04446393, -0.17452918,  0.73475671,  0.06790935,
       -1.0923452 ,  0.82569716,  1.00308582,  1.28013601, -0.66718339,
        1.50433497, -1.27116751,  0.49264902,  0.01143647,  0.10903517,
        1.00728652,  0.17632112,  1.2777135 , -0.34165236, -0.65641564,
        1.55609587,  0.32981078,  0.57025609, -1.42031846,  0.18178444,
       -0.66708497,  2.02308241,  0.98948743,  1.700386  ,  1.21627713,
       -0.36162867, -0.02286203,  0.16126265,  0.7511203 ,  0.71802651,
        0.90273704,  1.90437309, -1.07258526, -0.01281459,  0.0413982 ,
       -0.76009246,  1.6849151 , -0.42308146, -1.48221599, -0.67